### ISSUE TITLE
Mobile accessibility of corporate website 

### ISSUE THREAD

**Issue by sdoxsee** [p2-inc/phasetwo#2] opened 2022-11-10 13:30 UTC
![Screenshot_20221110-082911](https://user-images.githubusercontent.com/1173362/201104574-b37cc0e0-d393-492c-82fe-cff790db9d05.png)

**Comment by xgp** [comment] 2022-11-10 15:18
Duplicate of https://github.com/p2-inc/phasetwo-docs/issues/32

**Closed as completed by xgp** 2022-11-10 15:18 UTC
